export { db, getMigrationClient } from "./client"
export { withTenantContext } from "./rls"
export { storage } from "./storage"

export * from "./schema/index"

export { TenantRepo } from "./repos/TenantRepo"
export { UserRepo } from "./repos/UserRepo"
export { UserAppAccessRepo } from "./repos/UserAppAccessRepo"
export { RefreshTokenRepo } from "./repos/RefreshTokenRepo"
export { AppRepo } from "./repos/AppRepo"
export { AuditRepo } from "./repos/AuditRepo"
export { InviteTokenRepo } from "./repos/InviteTokenRepo"
export { PasswordResetRepo } from "./repos/PasswordResetRepo"
export { CertRepo } from "./repos/CertRepo"
export { AiConfigRepo } from "./repos/AiConfigRepo"

export type { Tenant, TenantFilters, TenantAddress, CreateTenantDTO } from "./repos/TenantRepo"
export type { App, AppSubscription, CreateAppDTO } from "./repos/AppRepo"
export type { CreateUserDTO, TenantMember } from "./repos/UserRepo"
export type { CreateRefreshTokenDTO } from "./repos/RefreshTokenRepo"
export type { AuditEntry, AuditAction, AuditTargetType, AuditFilters } from "./repos/AuditRepo"
export type { InviteToken, CreateInviteTokenDTO } from "./repos/InviteTokenRepo"
export type { PasswordResetToken, CreatePasswordResetDTO } from "./repos/PasswordResetRepo"
export type { EmpresaCertificado, CreateCertificadoDTO } from "./repos/CertRepo"
export type { AiConfigPublic, TenantAiProvider } from "./repos/AiConfigRepo"
